# Generated by Django 4.1.2 on 2023-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_email_showtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
