# Generated by Django 4.1.2 on 2023-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_showtime_datetime_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='datetime',
            field=models.DateField(),
        ),
    ]
