# Generated by Django 4.1.2 on 2023-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_showtime_endtime_showtime_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='availableseats',
            field=models.IntegerField(),
        ),
    ]
