# Generated by Django 4.1.2 on 2023-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_showtime_availableseats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=20),
        ),
    ]
