# Generated by Django 3.1 on 2023-03-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ear_health_professional', '0002_rating_review_patient_id'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_caregiver',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='add_caregiver',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='Health_Professional_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.health_professional_account'),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='Hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospital'),
        ),
        migrations.AddField(
            model_name='card_detail',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='card_detail',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='doctor_image',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='doctor_image',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='messages',
            name='Health_Professional_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.health_professional_account'),
        ),
        migrations.AddField(
            model_name='multipleimages',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='multipleimages',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='patient_account',
            name='Clinics_BranchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.clinics_branch'),
        ),
        migrations.AddField(
            model_name='patient_account',
            name='HospitalAccount_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.hospitalaccount'),
        ),
        migrations.AddField(
            model_name='patient_favorited',
            name='Health_Professional_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.health_professional_account'),
        ),
        migrations.AddField(
            model_name='patient_recent_visit',
            name='Health_Professional_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ear_health_professional.health_professional_account'),
        ),
    ]
