# Generated by Django 3.1 on 2023-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20230317_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='Completion',
            field=models.TextField(default='akjMaPmdwYqc2btwftgMOLe5H1/7BQpJUJMTLVdnVZbfcEVgXZvf8W8njyEEotQF8Q1hq850qnBFDLA/FZ9c6Q=='),
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='Problem',
            field=models.TextField(default='+4lISovpyV6DwPqRNcKmFvtDUyL3LLzPP9wCR3oIKMbT44gGXvC2F3EL1IvyY9MP3SmuuP5L69iN0ZJ8dJXEAQ=='),
        ),
    ]
