# Generated by Django 3.1 on 2023-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20230318_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_account',
            name='Patient_Account_Image',
            field=models.ImageField(default='dummyprofile.jpg', upload_to='Patient/'),
        ),
    ]
