# Generated by Django 4.1.2 on 2023-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.BooleanField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete'),
        ),
    ]
