# Generated by Django 4.1.2 on 2023-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=20),
        ),
    ]
