# Generated by Django 4.1.2 on 2023-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_block_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='block',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=255),
        ),
    ]
